TITLE_1: MAC5921
TITLE_2: Deep Learning
SUBTITLE_1: Disciplina de pós-graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro A …</li>
    <li>Artigo B …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/MAC5921-Deep-Learning
HERO_FILE: deep-learning.png